<?php

declare(strict_types=1);

/**
 * lote25.php — Limpieza: la documentación que mentía y el mapa que no preguntaba.
 *
 * REQUIERE el lote 24 aplicado.
 *
 * Sin migración y sin cambios de servidor.
 *
 * 1. `docs/testing.md` DECÍA QUE LA SUITE NUNCA SE HABÍA EJECUTADO
 *
 * Se ejecutó el 25 de agosto y quedó en 433 verdes. El documento llevaba desde
 * entonces afirmando lo contrario, y encima decía que los ficheros sin ejecutar
 * «llevan un aviso en su cabecera» — ninguno lo lleva ya. Reescrito con lo que
 * pasa de verdad:
 *
 *   • Que la suite se ejecutó, cuándo, y con qué resultado.
 *   • Qué se aprendió de aquel arranque: de 119 fallos, UNO era de la
 *     aplicación. El resto eran de las pruebas mismas.
 *   • Los ONCE ficheros de pruebas añadidos después, que no he ejecutado nunca,
 *     con sus nombres.
 *   • Qué sí se comprueba antes de entregar cada lote: `php -l`, `tsc`, paridad
 *     de diccionarios, y desde el lote 18 el DDL de cada migración contra un
 *     MySQL 8.0.46 real con el esquema entero cargado.
 *   • Una sección nueva sobre por qué todas las migraciones son reanudables, y
 *     la restricción de MySQL que costó un despliegue: una clave foránea con
 *     ON DELETE CASCADE no puede estar sobre una columna base de una columna
 *     generada STORED.
 *
 * 2. EL MAPA DE LA OFICINA YA NO LLAMA A GOOGLE SOLO
 *
 * El marco lo sirve Google, y con `loading="lazy"` se cargaba al hacer scroll:
 * en la práctica, Google recibía la IP de casi todo el que abriera la página de
 * contacto, hubiera querido ver el mapa o no.
 *
 * Ahora hay que pulsar. Quien quiere el mapa lo pide y lo ve; quien venía a
 * leer un teléfono no le entrega su IP a un tercero sin enterarse. Debajo queda
 * el enlace de siempre para abrirlo fuera.
 *
 * Tu política de privacidad YA declara «mapas y rutas» entre los subencargados,
 * así que esto no tapaba un hueco: reduce cuánta gente entra en ese supuesto.
 * Es criterio de ingeniería, no asesoramiento legal — la redacción del documento
 * sigue siendo cosa tuya y de tu abogado.
 *
 * Cómo se ejecuta, desde la raíz del repositorio:
 *
 *     php lote25.php            # aplica
 *     php lote25.php --dry-run  # dice qué haría y no toca nada
 */

$raiz = __DIR__;
$dry = in_array('--dry-run', $argv, true);
$hechos = []; $saltados = []; $errores = [];

function ruta(string $rel): string { global $raiz; return $raiz.DIRECTORY_SEPARATOR.$rel; }

function nuevo(string $rel, string $contenido): void
{
    global $dry, $hechos, $saltados, $errores;
    $destino = ruta($rel);
    if (is_file($destino) && file_get_contents($destino) === $contenido) { $saltados[] = "= {$rel}"; return; }
    $existia = is_file($destino);
    if ($dry) { $hechos[] = ($existia ? '~ ' : '+ ').$rel; return; }
    $dir = dirname($destino);
    if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) { $errores[] = "no se pudo crear el directorio {$dir}"; return; }
    if (file_put_contents($destino, $contenido) === false) { $errores[] = "no se pudo escribir {$rel}"; return; }
    $hechos[] = ($existia ? '~ ' : '+ ').$rel;
}

/**
 * Aplica trozos anclados. Si el resultado ya está, se salta; si el texto de
 * partida está una sola vez, se sustituye; si no, se aborta el fichero entero
 * sin escribir — un anclaje que no encaja significa que el fichero no es el que
 * este guion vio, y adivinar ahí es peor que parar.
 *
 * @param  list<array{0: string, 1: string}>  $pares
 */
function editar(string $rel, array $pares): void
{
    global $dry, $hechos, $saltados, $errores;
    $destino = ruta($rel);
    if (! is_file($destino)) { $errores[] = "falta {$rel} — ¿está en la raíz del repositorio?"; return; }
    $texto = file_get_contents($destino); $aplicados = 0; $yaEstaban = 0;
    foreach ($pares as $i => [$antes, $despues]) {
        if (str_contains($texto, $despues)) { $yaEstaban++; continue; }
        $veces = substr_count($texto, $antes);
        if ($veces !== 1) { $errores[] = "{$rel}: el trozo #".($i + 1)." no encaja ({$veces} coincidencias). No se tocó el fichero."; return; }
        $texto = str_replace($antes, $despues, $texto); $aplicados++;
    }
    if ($aplicados === 0) { $saltados[] = "= {$rel} ({$yaEstaban} trozo(s) ya estaban)"; return; }
    if ($dry) { $hechos[] = "~ {$rel} ({$aplicados} trozo(s))"; return; }
    if (file_put_contents($destino, $texto) === false) { $errores[] = "no se pudo escribir {$rel}"; return; }
    $hechos[] = "~ {$rel} ({$aplicados} trozo(s))";
}

foreach (['artisan', 'composer.json', 'app/Support/Navigation.php'] as $centinela) {
    if (! is_file(ruta($centinela))) {
        fwrite(STDERR, "Esto no parece la raíz del repositorio: falta {$centinela}.\n");
        exit(1);
    }
}

/* ── Ficheros nuevos ─────────────────────────────────────────────────── */


/* ── Ficheros que se modifican ───────────────────────────────────────── */

editar("docs/testing.md", [
    [base64_decode('c2VndW5kb3Mg4oCUMjQ2IGNsYXZlcyBmb3LDoW5lYXMsIDQ3IHRyaWdnZXJzLCA4OSBDSEVDS+KAlCB5IGhhY2VybG8gcG9yIGNhZGEgY2xhc2UKY29udmVydGlyw61hIGxhIHN1aXRlIGVuIGFsZ28gcXVlIG5hZGllIGVqZWN1dGEuIFNlIGNvbnN0cnV5ZSB1bmEgdmV6IHBvciBwcm9jZXNvCnkgY2FkYSBwcnVlYmEgcXVlIGVzY3JpYmUgc2UgZW52dWVsdmUgZW4gYERhdGFiYXNlVHJhbnNhY3Rpb25zYC4KCiMjIEVzdGFkbzogcGFydGUgZGUgbGEgc3VpdGUgTlVOQ0Egc2UgaGEgZWplY3V0YWRvCgpFc3RvIGhheSBxdWUgZGVjaXJsbyBhbnRlcyBxdWUgbmFkYS4KCkxvcyBmaWNoZXJvcyBkZSBgdGVzdHMvRmVhdHVyZS9DYXJyaWVyc2AsIGB0ZXN0cy9GZWF0dXJlL0N1c3RvbWVyc2AsCmB0ZXN0cy9GZWF0dXJlL0xvYWRzYCwgYHRlc3RzL0ZlYXR1cmUvRmxlZXRgLCBgdGVzdHMvRmVhdHVyZS9Eb2N1bWVudHNgLApgdGVzdHMvVW5pdC9DdXN0b21lcnNgLApgdGVzdHMvVW5pdC9GaW5hbmNlYCwgYHRlc3RzL1VuaXQvU2VjdXJpdHlgLCBgdGVzdHMvVW5pdC9TdXBwb3J0YCB5CmB0ZXN0cy9Vbml0L0kxOG4vTmF2aWdhdGlvbkxhYmVsc1Rlc3RgCnNlIGVzY3JpYmllcm9uIGVuIHVuIGVudG9ybm8gZG9uZGUgKipQZXN0IG5vIHNlIHB1ZWRlIGluc3RhbGFyKio6IGNvbXBvc2VyIGV4aWdlCmF1dGVudGljYXJzZSBjb250cmEgR2l0SHViIHBhcmEgbGFzIGRlcGVuZGVuY2lhcyBkZSBkZXNhcnJvbGxvLCB5IGVzZSBlbnRvcm5vIG5vCnBvZMOtYSBoYWNlcmxvLiBMbGV2YW4gdW4gYXZpc28gZW4gc3UgY2FiZWNlcmEuCgpMbyBxdWUgc8OtIGVzdMOhIGNvbXByb2JhZG8sIHkgY29udmllbmUgZGlzdGluZ3VpcmxvOgoKfCBRdcOpIHwgQ8OzbW8gc2UgY29tcHJvYsOzIHwKfC0tLXwtLS18CnwgRWwgY29tcG9ydGFtaWVudG8gcXVlIGFmaXJtYW4gfCBBIG1hbm8sIGNvbiBwZXRpY2lvbmVzIEhUVFAgcmVhbGVzIHkgY29uIG5hdmVnYWRvciwgY29udHJhIGxhIGFwbGljYWNpw7NuIGVuIG1hcmNoYSB8CnwgUXVlIGxhcyAxNiBydXRhcyBxdWUgdXNhbiBleGlzdGVuIHwgUmVzb2x2acOpbmRvbGFzIGNvbnRyYSBlbCBlbnJ1dGFkb3IgfAp8IFF1ZSBsb3MgY29tcG9uZW50ZXMgSW5lcnRpYSBleGlzdGVuIHwgQ29tcHJvYmFuZG8gbG9zIGZpY2hlcm9zIGVuIGByZXNvdXJjZXMvanMvcGFnZXNgIHwKfCBRdWUgbGFzIGNvbHVtbmFzIGNvbnN1bHRhZGFzIGV4aXN0ZW4gfCBgU2NoZW1hOjpoYXNDb2x1bW5gIHNvYnJlIGxhcyA5IHRhYmxhcyBpbXBsaWNhZGFzIHwKfCBRdWUgbGFzIGNsYXNlcyB5IG3DqXRvZG9zIGV4aXN0ZW4gfCBgY2xhc3NfZXhpc3RzYCAvIGBtZXRob2RfZXhpc3RzYCB8CnwgTG9zIHZhbG9yZXMgZGUgYE5hbWVLZXlUZXN0YCB8IExsYW1hbmRvIGEgYE5hbWVLZXk6OmZvcigpYCBjb24gY2FkYSBwYXIgZGVsIGRhdGFzZXQgfAp8IExhcyBhc2VyY2lvbmVzIGRlIGBOYXZpZ2F0aW9uVGVzdGAgfCBFamVjdXRhbmRvIGBOYXZpZ2F0aW9uOjpmb3IoKWAgY29uIGxvcyBzZWlzIHJvbGVzIHwKfCAqKkxhcyAyNiBhc2VyY2lvbmVzIGRlIGBDYWxjdWxhdG9yVGVzdGAqKiB8IEVqZWN1dGFuZG8gYENhbGN1bGF0b3JgIHkgYE1vbmV5YCBjb24gY2FkYSBjYXNvLCB1bmEgcG9yIHVuYSB8CnwgTGFzIGRlbCBncmFmbyBlbiBgTG9hZFRyYW5zaXRpb25UZXN0YCB8IEVqZWN1dGFuZG8gYFRyYW5zaXRpb25zYCBjb24gbG9zIHRyZWNlIGVzdGFkb3MgfAp8IExhcyBjbGF2ZXMgZGUgYGxvYWRzLmJsb2NraW5nLipgIHkgYGxvYWRzLmFzc2lnbi4qYCB8IENvbXByb2JhZGFzIGVuIGxvcyBkb3MgZGljY2lvbmFyaW9zIHwKfCBFbCBjaWNsbyBjb21wbGV0byBkZSBgTG9hZEZvcm1UZXN0YCB8IFJlY29ycmlkbyBwb3IgSFRUUDogY2FyZ2EgY3JlYWRhLCBhc2lnbmFkYSwgZGVzcGFjaGFkYSB5IGVudHJlZ2FkYSB8CnwgTG9zIGRvcyBwZXJtaXNvcyBkZSBlZGljacOzbiB8IFByb2JhZG9zIGVuIGxhcyBkb3MgZGlyZWNjaW9uZXMgY29uIGRlc3BhY2hhZG9yIHkgY29udGFiaWxpZGFkIHwKfCAqKkxhcyAxMiBhc2VyY2lvbmVzIGRlIGBTZW5zaXRpdmVOdW1iZXJUZXN0YCoqIHwgRWplY3V0YW5kbyBgU2Vuc2l0aXZlTnVtYmVyYCBjb24gY2FkYSBjYXNvLCB1bmEgcG9yIHVuYSB8CnwgUXVlIGxhIGxpY2VuY2lhIG5vIHZpYWplIGFsIGNsaWVudGUgfCBJbnNwZWNjaW9uYW5kbyBsYSByZXNwdWVzdGEgSFRUUCBjb24gbG9zIGNpbmNvIHJvbGVzIHwKfCBFbCBhcnJhbnF1ZSBlbiBmcsOtbyB8IENvbmR1Y3RvciB5IGNhbWnDs24gY3JlYWRvcyBwb3IgSFRUUCB5IHVzYWRvcyBlbiB1bmEgY2FyZ2EgZGVzcGFjaGFkYSB8CnwgTGEgc3ViaWRhIHkgbGEgZGVzY2FyZ2EgZGUgdW4gZmljaGVybyB8IFVuIFBERiByZWFsIHN1YmlkbywgZGVzY2FyZ2FkbyBwb3IgVVJMIGZpcm1hZGEgeSBjb21wYXJhZG8gYnl0ZSBhIGJ5dGUgfAp8IFF1ZSBsYSBmaXJtYSBzZWEgbGEgY3JlZGVuY2lhbCB8IFNpbiBmaXJtYSA0MDMsIGZpcm1hIG1hbmlwdWxhZGEgNDAzLCBmaXJtYSB2w6FsaWRhIHNpbiBzZXNpw7NuIDIwMCB8CnwgTG9zIG1lbnNhamVzIGRlIHZhbGlkYWNpw7NuIGVuIGVzcGHDsW9sIHwgVHJlcyBmb3JtdWxhcmlvcyBkaXN0aW50b3MsIGNvbXByb2JhZG9zIHRyYXMgY3JlYXIgYGxhbmcvZXMvdmFsaWRhdGlvbi5waHBgIHwKfCBTaW50YXhpcyBQSFAgfCBgcGhwIC1sYCBzb2JyZSBjYWRhIGZpY2hlcm8gfAoKTG8gcXVlICoqbm8qKiBlc3TDoSBjb21wcm9iYWRvIGVzIGxhIG1lY8OhbmljYSBkZSBQZXN0OiBsYSBmaXJtYSBleGFjdGEgZGUgdW5hCmFzZXJjacOzbiwgdW4gYC0+d2l0aCgpYCBtYWwgZm9ybWFkbywgdW4gaGVscGVyIHF1ZSBubyBleGlzdGUgZW4gbGEgdmVyc2nDs24KaW5zdGFsYWRhLgoKKipBbCBlamVjdXRhcmxhcyBwb3IgcHJpbWVyYSB2ZXosIGRpc3RpbmdhIGxvcyBkb3MgdGlwb3MgZGUgZmFsbG8uKiogU2kgYWxnbyBzZQpyb21wZSBwb3IgbGEgRk9STUEg4oCUbcOpdG9kbyBkZXNjb25vY2lkbywgYXNlcmNpw7NuIGNvbiBvdHJhIGZpcm1h4oCUIGVzIHVuYSBlcnJhdGEKbcOtYSB5IHNlIGFycmVnbGEuIFNpIGFsZ28gZmFsbGEgcG9yIGVsIFZBTE9SIGVzcGVyYWRvLCBlc28gc8OtIGVzIHVuYSByZWdyZXNpw7NuCmRlIHZlcmRhZCB5IGhheSBxdWUgbWlyYXJsYS4KCiMjIEPDs21vIGVzdMOhbiBvcmdhbml6YWRhcwoKLSAqKmB0ZXN0cy9Vbml0YCoqIOKAlCBzaW4gYmFzZSBkZSBkYXRvcyB5IHNpbiBhcnJhbmNhciBsYSBhcGxpY2FjacOzbi4gTGEK'), base64_decode('c2VndW5kb3Mg4oCUMjQ2IGNsYXZlcyBmb3LDoW5lYXMsIDQ3IHRyaWdnZXJzLCA4OSBDSEVDS+KAlCB5IGhhY2VybG8gcG9yIGNhZGEgY2xhc2UKY29udmVydGlyw61hIGxhIHN1aXRlIGVuIGFsZ28gcXVlIG5hZGllIGVqZWN1dGEuIFNlIGNvbnN0cnV5ZSB1bmEgdmV6IHBvciBwcm9jZXNvCnkgY2FkYSBwcnVlYmEgcXVlIGVzY3JpYmUgc2UgZW52dWVsdmUgZW4gYERhdGFiYXNlVHJhbnNhY3Rpb25zYC4KCiMjIEVzdGFkbzogcXXDqSBzZSBoYSBlamVjdXRhZG8geSBxdcOpIG5vCgpMYSBzdWl0ZSAqKnNlIGVqZWN1dMOzIHkgcXVlZMOzIGVuIHZlcmRlKiogZWwgMjUgZGUgYWdvc3RvIGRlIDIwMjY6CgpgYGAKVGVzdHM6ICA0MzMgcGFzc2VkICgzMTg3IGFzc2VydGlvbnMpCmBgYAoKQW50ZXMgZGUgZXNvLCBidWVuYSBwYXJ0ZSBzZSBoYWLDrWEgZXNjcml0byBzaW4gcG9kZXIgZWplY3V0YXJzZS4gQXF1ZWwgcHJpbWVyCmFycmFucXVlIGRlasOzIHVuYSBsZWNjacOzbiBxdWUgY29udmllbmUgY29uc2VydmFyLCBwb3JxdWUgbm8gZXMgbGEgcXVlIHNlIGVzcGVyYToKZGUgbG9zIDExOSBmYWxsb3MgaW5pY2lhbGVzLCAqKnVubyBzb2xvKiogZXJhIHVuIGRlZmVjdG8gZGUgbGEgYXBsaWNhY2nDs24g4oCUbG9zCm1pbGlzZWd1bmRvcyBxdWUgc2UgcGVyZMOtYW4gZW4gbGFzIGVzY3JpdHVyYXMgY3J1ZGFzLCBob3kgcmVzdWVsdG9zIGNvbgpgQXBwXFN1cHBvcnRcRGF0YWJhc2VcTWlsbGlzZWNvbmRHcmFtbWFyYOKAlC4gRWwgcmVzdG8gZXJhbiBkZWZlY3RvcyBkZSBsYXMKcHJvcGlhcyBwcnVlYmFzOiBkb3MgZmFsbG9zIGVuIGBzaWduSW4oKWAsIGRpZXogYGFzc2VydEZvcmJpZGRlbigpYCBtYWwgcHVlc3RhcywKdW4gZml4dHVyZSBhbCBxdWUgbGUgZmFsdGFiYW4gZG9jdW1lbnRvcyBvYmxpZ2F0b3Jpb3MgeSB2YXJpb3MgbsO6bWVyb3MgbcOhZ2ljb3MKY2FkdWNhZG9zLiBEb3MgZmFsbG9zIHF1ZSBwYXJlY8OtYW4gYWd1amVyb3MgZGUgc2VndXJpZGFkIHJlc3VsdGFyb24gc2VyIGVmZWN0b3MKZGVsIHNlZ3VuZG8gZGVmZWN0byBkZSBgc2lnbkluKClgLgoKIyMjIExvIHF1ZSBzZSBoYSBhw7FhZGlkbyBERVNQVcOJUyB5IG5vIGhlIGVqZWN1dGFkbyBudW5jYQoKRXN0b3Mgb25jZSBmaWNoZXJvcyBzb24gcG9zdGVyaW9yZXMgYSBhcXVlbCBhcnJhbnF1ZSBlbiB2ZXJkZToKCmBgYAp0ZXN0cy9GZWF0dXJlL0NhcnJpZXJzL0NhcnJpZXJDb250YWN0c1Rlc3QucGhwCnRlc3RzL0ZlYXR1cmUvRG9jdW1lbnRzL1VzZWREb2N1bWVudFR5cGVzVGVzdC5waHAKdGVzdHMvRmVhdHVyZS9GYWN0b3JpbmcvRmFjdG9yaW5nVGVzdC5waHAKdGVzdHMvRmVhdHVyZS9GaW5hbmNlL0ludm9pY2VUZXN0LnBocAp0ZXN0cy9GZWF0dXJlL0ZpbmFuY2UvU2V0dGxlbWVudFRlc3QucGhwCnRlc3RzL0ZlYXR1cmUvRmxlZXQvRHJpdmVyUXVhbGlmaWNhdGlvblRlc3QucGhwCnRlc3RzL0ZlYXR1cmUvRm1jc2EvQ2Fycmllckxvb2t1cFRlc3QucGhwCnRlc3RzL0ZlYXR1cmUvR2VvL0NvdW50cnlTdGF0ZVRlc3QucGhwCnRlc3RzL0ZlYXR1cmUvTG9hZHMvTG9hZFJlcXVpcmVtZW50c1Rlc3QucGhwCnRlc3RzL1VuaXQvR2VvL1JlZ2lvblBhcml0eVRlc3QucGhwCnRlc3RzL1VuaXQvTG9hZHMvRHJpdmVyRWxpZ2liaWxpdHlUZXN0LnBocApgYGAKCk3DoXMgbG9zIHJldG9xdWVzIGEgYFNjaGVtYUFncmVlbWVudFRlc3RgIChlbCByZWN1ZW50byBkZSBtb2RlbG9zKSB5IGEKYE5hdmlnYXRpb25UZXN0YC4KCioqTm8gbG9zIGhlIGVqZWN1dGFkbyBuaSB1bmEgdmV6LioqIEVsIGVudG9ybm8gZG9uZGUgc2UgZXNjcmliZW4gbm8gYWxjYW56YQpwYWNrYWdpc3QsIGFzw60gcXVlIG5vIGhheSBgdmVuZG9yL2AsIHkgc2luIGB2ZW5kb3IvYCBubyBoYXkgYGFydGlzYW5gIG5pIFBlc3QuCkVzbyBubyBoYSBjYW1iaWFkby4KCiMjIyBMbyBxdWUgc8OtIHNlIGNvbXBydWViYSBhbnRlcyBkZSBlbnRyZWdhciBjYWRhIGxvdGUKCnwgUXXDqSB8IEPDs21vIHwKfC0tLXwtLS18CnwgU2ludGF4aXMgUEhQIHwgYHBocCAtbGAgc29icmUgY2FkYSBmaWNoZXJvIHRvY2FkbyB8CnwgVGlwb3MgZGUgVHlwZVNjcmlwdCB8IGB0c2MgLS1ub0VtaXRgIHNvYnJlIGNhZGEgYC50c3hgIHRvY2FkbyB8CnwgUGFyaWRhZCBkZSBkaWNjaW9uYXJpb3MgfCBFTiB5IEVTIGNvbXBhcmFkb3MgY2xhdmUgYSBjbGF2ZSB8CnwgQ2xhdmVzIHVzYWRhcyB5IG5vIHRyYWR1Y2lkYXMgfCBFeHRyYcOtZGFzIGRlbCBUU1ggeSBkZWwgUEhQIHkgY3J1emFkYXMgY29uIGVsIGRpY2Npb25hcmlvIHwKfCAqKkVsIERETCBkZSBjYWRhIG1pZ3JhY2nDs24qKiB8IEVqZWN1dGFkbyBjb250cmEgdW4gKipNeVNRTCA4LjAuNDYgcmVhbCoqIGNvbiBsb3MgcXVpbmNlIGZpY2hlcm9zIGRlbCBlc3F1ZW1hIGNhcmdhZG9zOiA5MyB0YWJsYXMsIDQ3IHRyaWdnZXJzLCAyNDYgY2xhdmVzIGZvcsOhbmVhcyB8CnwgUXVlIGxhIG1pZ3JhY2nDs24gc2UgcHVlZGEgcmVhbnVkYXIgfCBFamVjdXRhZGEgZGVzZGUgY2Vybywgc29icmUgbG8geWEgYXBsaWNhZG8sIHkgZGVzZGUgZXN0YWRvcyBhIG1lZGlhcyB8CnwgUXVlIGVsIGluc3RhbGFkb3IgZGVsIGxvdGUgYWNpZXJ0ZSB8IEFwbGljYWRvIHNvYnJlIHVuYSBjb3BpYSBsaW1waWEgeSBjb21wYXJhZG8gYnl0ZSBhIGJ5dGU7IHkgZWplY3V0YWRvIGRvcyB2ZWNlcyBwYXJhIGNvbXByb2JhciBxdWUgZXMgaWRlbXBvdGVudGUgfAoKRXNlIGJhbmNvIGRlIE15U1FMIGV4aXN0ZSBkZXNkZSBlbCBsb3RlIDE4LCB5IG5hY2nDsyBkZSB1biBmYWxsbzogZWwgbG90ZSAxNQp0dW1iw7MgdW4gZGVzcGxpZWd1ZSBjb24gdW4gYEVSUk9SIDEyMTVgIHF1ZSBzZSByZXByb2R1Y2UgZW4gc2VndW5kb3MgY29uIGxhIGJhc2UKZGVsYW50ZS4gVmVyIG3DoXMgYWJham8uCgojIyMgQWwgZWplY3V0YXIgbG9zIG9uY2UsIGRpc3RpbmdhIGxvcyBkb3MgdGlwb3MgZGUgZmFsbG8KClNpIGFsZ28gc2Ugcm9tcGUgcG9yIGxhICoqZm9ybWEqKiDigJR1biBtw6l0b2RvIHF1ZSBubyBleGlzdGUsIHVuYSBhc2VyY2nDs24gY29uCm90cmEgZmlybWEsIHVuIGZpeHR1cmUgYWwgcXVlIGxlIGZhbHRhIHVuIGNhbXBvIG9ibGlnYXRvcmlvIGRlbCBlc2NlbmFyaW/igJQgZXMKdW5hIGVycmF0YSBtw61hIHkgc2UgYXJyZWdsYSBlbiBlbCBmaWNoZXJvIGRlIHBydWViYXMuIFNpIGFsZ28gZmFsbGEgcG9yIGVsCioqdmFsb3IgZXNwZXJhZG8qKiwgZXNvIHPDrSBtZXJlY2UgbWlyYXJzZTogcHVlZGUgc2VyIHVuYSByZWdyZXNpw7NuIGRlIHZlcmRhZC4KCkxhIHByb3BvcmNpw7NuIGRlbCBwcmltZXIgYXJyYW5xdWUgKDExOCBkZSAxMTkgZmFsbG9zIGVyYW4gZGUgbGFzIHBydWViYXMsIG5vIGRlCmxhIGFwbGljYWNpw7NuKSBzdWdpZXJlIHF1w6kgZXNwZXJhciwgcGVybyBubyBsbyBnYXJhbnRpemEuCgojIyBNaWdyYWNpb25lczogcG9yIHF1w6kgdG9kYXMgc29uIHJlYW51ZGFibGVzCgpNeVNRTCBubyB0aWVuZSBEREwgdHJhbnNhY2Npb25hbCwgeSBMYXJhdmVsIG1hbmRhICoqdW4gYGFsdGVyIHRhYmxlYCBwb3IKY29sdW1uYSoqLiBVbmEgbWlncmFjacOzbiBxdWUgbXVlcmEgYSBtaXRhZCBkZWphIG1lZGlhIHRhYmxhIHB1ZXN0YSB5ICoqbm8gc2UKcmVnaXN0cmEqKiBlbiBgbWlncmF0aW9uc2A6IGFsIHJlaW50ZW50YXJsYSBzZSBlc3RyZWxsYSBjb250cmEgbG8gcXVlIHlhIGVzdMOhCihgRVJST1IgMTA2MCBEdXBsaWNhdGUgY29sdW1uYCkuCgpQYXPDsyBkb3MgdmVjZXMgZW4gZGVzcGxpZWd1ZXMgcmVhbGVzLCBlbiBhZ29zdG8gZGUgMjAyNi4gTGEgcHJpbWVyYSBzZSBhcnJlZ2zDswpjb21vIGNhc28gcGFydGljdWxhcjsgbGEgc2VndW5kYSBvYmxpZ8OzIGEgc2FjYXIgbGEgcmVnbGE6Cgo+IFRvZGEgbWlncmFjacOzbiBjb21wcnVlYmEsIHBhc28gYSBwYXNvLCBzaSBsbyBxdWUgdmEgYSBoYWNlciB5YSBlc3TDoSBoZWNobyDigJQKPiBjb2x1bW5hcyBjb24gYFNjaGVtYTo6aGFzQ29sdW1uYCwgQ0hFQ0sgeSBjbGF2ZXMgZm9yw6FuZWFzIGNvbnRyYQo+IGBpbmZvcm1hdGlvbl9zY2hlbWEudGFibGVfY29uc3RyYWludHNgLCDDrW5kaWNlcyBjb250cmEKPiBgaW5mb3JtYXRpb25fc2NoZW1hLnN0YXRpc3RpY3NgLgoKRWplY3V0YXIgdW5hIGRvcyB2ZWNlcyBzZWd1aWRhcyB0aWVuZSBxdWUgZGFyIGVsIG1pc21vIHJlc3VsdGFkbyBxdWUgZWplY3V0YXJsYQp1bmEuIGBkb3duKClgIHZhIGlndWFsIGRlIHByb3RlZ2lkby4KClkgdW5hIHJlc3RyaWNjacOzbiBkZSBNeVNRTCBxdWUgY29zdMOzIHVuIGRlc3BsaWVndWUgZW50ZXJvLCBwb3Igc2kgdnVlbHZlIGEKYXBhcmVjZXI6Cgo+IFVuYSBjbGF2ZSBmb3LDoW5lYSBjb24gYE9OIERFTEVURSBDQVNDQURFYCAqKm5vIHB1ZWRlKiogZXN0YXIgc29icmUgdW5hIGNvbHVtbmEKPiBxdWUgc2VhIGJhc2UgZGUgdW5hIGNvbHVtbmEgZ2VuZXJhZGEgKipTVE9SRUQqKi4KCkVsIGVzcXVlbWEgZW11bGEgw61uZGljZXMgw7puaWNvcyBwYXJjaWFsZXMgY29uIGNvbHVtbmFzIGdlbmVyYWRhcyBTVE9SRUQgcG9yIHRvZGFzCnBhcnRlcywgYXPDrSBxdWUgZWwgY2hvcXVlIGVzIGbDoWNpbCBkZSBwcm92b2Nhci4gTGEgc2FsaWRhIGVzIHF1ZSBsYSBjb2x1bW5hCmdlbmVyYWRhIG5vIGRlcGVuZGEgZGUgbGEgY29sdW1uYSBkZSBsYSBjbGF2ZSBmb3LDoW5lYTogc2UgbWV0ZSBlc2EgY29sdW1uYSBlbiBlbArDjU5ESUNFLCBxdWUgbm8gZXN0w6Egc3VqZXRvIGEgbGEgcmVzdHJpY2Npw7NuLiBWZXIKYDIwMjZfMDhfMjhfMTAwMDAwX2NyZWF0ZV9jYXJyaWVyX2NvbnRhY3RzLnBocGAuCgojIyBDw7NtbyBlc3TDoW4gb3JnYW5pemFkYXMKCi0gKipgdGVzdHMvVW5pdGAqKiDigJQgc2luIGJhc2UgZGUgZGF0b3MgeSBzaW4gYXJyYW5jYXIgbGEgYXBsaWNhY2nDs24uIExhCg==')],
    [base64_decode('LSBObyBoYXkgcHJ1ZWJhcyBkZSBsYXMgcGFudGFsbGFzIGVuIFJlYWN0LiBMYSB2ZXJpZmljYWNpw7NuIGRlIGxhIGludGVyZmF6IGhhCiAgc2lkbyBjb24gbmF2ZWdhZG9yIGEgbWFuby4KLSBgdGVzdHMvU3VwcG9ydC9TY2VuYXJpby5waHBgIHZpdmUgYmFqbyBlbCBlc3BhY2lvIGBUZXN0c1xgLCBxdWUgZXN0w6EgZW4KICBgYXV0b2xvYWQtZGV2YC4gQ29uIGxhcyBkZXBlbmRlbmNpYXMgZGUgZGVzYXJyb2xsbyBhdXNlbnRlcyBubyBzZSBhdXRvY2FyZ2E7CiAgc2UgY29tcHJvYsOzIGNhcmdhbmRvIGVsIGZpY2hlcm8gYSBtYW5vLiBDb24gYGNvbXBvc2VyIGluc3RhbGxgIGNvbXBsZXRvLCBzZQogIHJlc3VlbHZlIHNvbG8uCg=='), base64_decode('LSBObyBoYXkgcHJ1ZWJhcyBkZSBsYXMgcGFudGFsbGFzIGVuIFJlYWN0LiBMYSB2ZXJpZmljYWNpw7NuIGRlIGxhIGludGVyZmF6IGhhCiAgc2lkbyBjb24gbmF2ZWdhZG9yIGEgbWFuby4KLSBgdGVzdHMvU3VwcG9ydC9TY2VuYXJpby5waHBgIHZpdmUgYmFqbyBlbCBlc3BhY2lvIGBUZXN0c1xgLCBxdWUgZXN0w6EgZW4KICBgYXV0b2xvYWQtZGV2YC4gQ29uIGxhcyBkZXBlbmRlbmNpYXMgZGUgZGVzYXJyb2xsbyBhdXNlbnRlcyBubyBzZSBhdXRvY2FyZ2E7CiAgY29uIGBjb21wb3NlciBpbnN0YWxsYCBjb21wbGV0bywgc2UgcmVzdWVsdmUgc29sby4KLSBObyBoYXkgcHJ1ZWJhcyBkZWwgYWRhcHRhZG9yIFJFQUwgZGUgRk1DU0EgY29udHJhIGVsIHNlcnZpY2lvIGRlIHZlcmRhZC4KICBgUWNNb2JpbGVEaXJlY3RvcnlgIHNlIHBydWViYSBjb24gYEh0dHA6OmZha2UoKWAsIGxvIHF1ZSBkZW11ZXN0cmEgZWwgbWFwZW8gZGUKICBsYSByZXNwdWVzdGEsICoqbm8qKiBlbCBjb250cmF0byBkZWwgcHJvdmVlZG9yLiBMYSBwcmltZXJhIGNvbnN1bHRhIGNvbiBjbGF2ZQogIGRlIHZlcmRhZCBwdWVkZSBleGlnaXIgYWp1c3RhciBub21icmVzIGRlIGNhbXBvLgo=')],
]);

editar("resources/js/components/Marketing/OfficeMap.tsx", [
    [base64_decode('aW1wb3J0IHsgdXNlUGFnZSB9IGZyb20gJ0BpbmVydGlhanMvcmVhY3QnCmltcG9ydCB7IHVzZUkxOG4gfSBmcm9tICdAL2xpYi9pMThuJwppbXBvcnQgdHlwZSB7IENvbXBhbnlDb250YWN0IH0gZnJvbSAnQC90eXBlcy9tYXJrZXRpbmcnCgovKioKICogRWwgbWFwYSBkZSBsYSBvZmljaW5hLgogKgogKiBMYSBVUkwgbGEgY29uc3RydXllIGVsIHNlcnZpZG9yIGEgcGFydGlyIGRlbCBkb21pY2lsaW8gKHZlcgogKiBBcHBcU3VwcG9ydFxDb21wYW55KSwgYXPDrSBxdWUgdW5hIGVtcHJlc2EgY2xpZW50ZSBiYWpvIHN1IHByb3BpbyBkb21pbmlvIHZlCiAqIFNVIG9maWNpbmEgc2luIHF1ZSBhcXXDrSBoYXlhIHF1ZSBkZWNpZGlyIG5hZGEuCiAqCiAqIGBsb2FkaW5nPSJsYXp5ImAgbm8gZXMgdW5hIG9wdGltaXphY2nDs24gZGUgbcOhczogZWwgbWFyY28gbG8gc2lydmUgdW4gdGVyY2VybywKICogeSBhc8OtIG5vIHNlIGNhcmdhIOKAlG5pIHNlIGxlIGRhIGxhIElQIGRlbCB2aXNpdGFudGXigJQgaGFzdGEgcXVlIGVsIG1hcGEgZXN0w6EgYQogKiBwdW50byBkZSBlbnRyYXIgZW4gcGFudGFsbGEuIFNpIGVzbyBzaWd1ZSBzb2JyYW5kbywgYGNvbXBhbnkubWFwLnByb3ZpZGVyYCBlbgogKiBsYSBjb25maWd1cmFjacOzbiB2YWxlICdub25lJyB5IGVzdG8gbm8gcGludGEgbmFkYS4KICovCmV4cG9ydCBmdW5jdGlvbiBPZmZpY2VNYXAoKSB7CiAgY29uc3QgeyB0IH0gPSB1c2VJMThuKCkKICBjb25zdCB7IGNvbXBhbnkgfSA9IHVzZVBhZ2U8eyBjb21wYW55OiBDb21wYW55Q29udGFjdCB8IG51bGwgfT4oKS5wcm9wcwoKICBpZiAoY29tcGFueSA9PT0gbnVsbCB8fCBjb21wYW55Lm1hcEVtYmVkVXJsID09PSBudWxsKSB7CiAgICByZXR1cm4gbnVsbAogIH0KCiAgcmV0dXJuICgKICAgIDxpZnJhbWUK'), base64_decode('aW1wb3J0IHsgdXNlUGFnZSB9IGZyb20gJ0BpbmVydGlhanMvcmVhY3QnCmltcG9ydCB7IHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnCmltcG9ydCB7IHVzZUkxOG4gfSBmcm9tICdAL2xpYi9pMThuJwppbXBvcnQgdHlwZSB7IENvbXBhbnlDb250YWN0IH0gZnJvbSAnQC90eXBlcy9tYXJrZXRpbmcnCgovKioKICogRWwgbWFwYSBkZSBsYSBvZmljaW5hLCBxdWUgTk8gc2UgY2FyZ2EgaGFzdGEgcXVlIGFsZ3VpZW4gbG8gcGlkZS4KICoKICogTGEgVVJMIGxhIGNvbnN0cnV5ZSBlbCBzZXJ2aWRvciBhIHBhcnRpciBkZWwgZG9taWNpbGlvICh2ZXIKICogQXBwXFN1cHBvcnRcQ29tcGFueSksIGFzw60gcXVlIHVuYSBlbXByZXNhIGNsaWVudGUgYmFqbyBzdSBwcm9waW8gZG9taW5pbyB2ZQogKiBTVSBvZmljaW5hIHNpbiBxdWUgYXF1w60gaGF5YSBxdWUgZGVjaWRpciBuYWRhLgogKgogKiBQT1IgUVXDiSBIQVkgUVVFIFBVTFNBUgogKgogKiBFbCBtYXJjbyBsbyBzaXJ2ZSBHb29nbGUuIEVuIGN1YW50byBzZSBjYXJnYSwgR29vZ2xlIHJlY2liZSBsYSBJUCBkZWwKICogdmlzaXRhbnRlLCBzdSBuYXZlZ2Fkb3IgeSBsYSBww6FnaW5hIGRlc2RlIGxhIHF1ZSB2aWVuZSDigJQgaGF5YSBpbnRlcmFjdHVhZG8gbwogKiBubyBjb24gZWwgbWFwYS4gQ29uIGBsb2FkaW5nPSJsYXp5ImAgZXNvIHBhc2FiYSBhbCBoYWNlciBzY3JvbGwgaGFzdGEgYXF1w60sCiAqIHF1ZSBlbiBsYSBwcsOhY3RpY2EgZXMgwqthIGNhc2kgdG9kbyBlbCBxdWUgYWJyYSBsYSBww6FnaW5hIGRlIGNvbnRhY3RvwrsuCiAqCiAqIENhcmdhcmxvIHNvbG8gYWwgcHVsc2FyIGNhbWJpYSBxdWnDqW4gZGVjaWRlLiBRdWllbiBxdWllcmUgdmVyIGVsIG1hcGEgbG8gcGlkZQogKiB5IGxvIHZlOyBxdWllbiBzb2xvIHZlbsOtYSBhIGxlZXIgdW4gdGVsw6lmb25vIG5vIGxlIGVudHJlZ2Egc3UgSVAgYSB1biB0ZXJjZXJvCiAqIHNpbiBlbnRlcmFyc2UuIExhIHBvbMOtdGljYSBkZSBwcml2YWNpZGFkIHlhIGRlY2xhcmEgwqttYXBhcyB5IHJ1dGFzwrsgZW50cmUgbG9zCiAqIHN1YmVuY2FyZ2Fkb3MsIGFzw60gcXVlIGVzdG8gbm8gdGFwYSB1biBodWVjbyBsZWdhbDogcmVkdWNlIGN1w6FudGEgZ2VudGUgZW50cmEKICogZW4gZXNlIHN1cHVlc3RvLCBxdWUgZXMgY29zYSBkaXN0aW50YSB5IG3DoXMgYmFyYXRhIHF1ZSB1bmEgY29uc3VsdGEganVyw61kaWNhLgogKgogKiBFc3RvIGVzIGNyaXRlcmlvIGRlIGluZ2VuaWVyw61hLCBubyBhc2Vzb3JhbWllbnRvIGxlZ2FsLgogKgogKiBTaSBlbCBtYXBhIHNvYnJhIGRlbCB0b2RvLCBgY29tcGFueS5tYXAucHJvdmlkZXJgIGVuIGxhIGNvbmZpZ3VyYWNpw7NuIHZhbGUKICogJ25vbmUnIHkgZXN0byBubyBwaW50YSBuYWRhLgogKi8KZXhwb3J0IGZ1bmN0aW9uIE9mZmljZU1hcCgpIHsKICBjb25zdCB7IHQgfSA9IHVzZUkxOG4oKQogIGNvbnN0IHsgY29tcGFueSB9ID0gdXNlUGFnZTx7IGNvbXBhbnk6IENvbXBhbnlDb250YWN0IHwgbnVsbCB9PigpLnByb3BzCiAgY29uc3QgW2Nhcmdhciwgc2V0Q2FyZ2FyXSA9IHVzZVN0YXRlKGZhbHNlKQoKICBpZiAoY29tcGFueSA9PT0gbnVsbCB8fCBjb21wYW55Lm1hcEVtYmVkVXJsID09PSBudWxsKSB7CiAgICByZXR1cm4gbnVsbAogIH0KCiAgaWYgKCEgY2FyZ2FyKSB7CiAgICByZXR1cm4gKAogICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBoLTU2IHctZnVsbCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTMgcm91bmRlZCBib3JkZXIgYm9yZGVyLWRhc2hlZCBib3JkZXItc3RlZWwtMzAwIGJnLXN0ZWVsLTUwIHB4LTQgdGV4dC1jZW50ZXIiPgogICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1zbSB0ZXh0LXN0ZWVsLTcwMCI+e3QoJ21hcmtldGluZy5jb21wYW55Lm1hcENvbnNlbnQnKX08L3A+CgogICAgICAgIDxidXR0b24KICAgICAgICAgIHR5cGU9ImJ1dHRvbiIKICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHNldENhcmdhcih0cnVlKX0KICAgICAgICAgIGNsYXNzTmFtZT0icm91bmRlZCBiZy1uYXZ5LTcwMCBweC00IHB5LTIgdGV4dC1zbSBmb250LXNlbWlib2xkIHRleHQtd2hpdGUgdHJhbnNpdGlvbiBob3ZlcjpiZy1uYXZ5LTgwMCIKICAgICAgICA+CiAgICAgICAgICB7dCgnbWFya2V0aW5nLmNvbXBhbnkubWFwTG9hZCcpfQogICAgICAgIDwvYnV0dG9uPgoKICAgICAgICB7LyogU2llbXByZSBoYXkgdW5hIHNhbGlkYSBxdWUgbm8gcGFzYSBwb3IgZWwgdGVyY2VybzogbGEgZGlyZWNjacOzbiB5YQogICAgICAgICAgICBlc3TDoSBlc2NyaXRhIGVuY2ltYSwgeSBlc3RlIGVubGFjZSBhYnJlIGVsIG1hcGEgZW4gc3Ugc2l0aW8sIGNvbgogICAgICAgICAgICBsYSBkZWNpc2nDs24gdG9tYWRhIGEgbGEgdmlzdGEuICovfQogICAgICAgIHtjb21wYW55LmRpcmVjdGlvbnNVcmwgPyAoCiAgICAgICAgICA8YQogICAgICAgICAgICBocmVmPXtjb21wYW55LmRpcmVjdGlvbnNVcmx9CiAgICAgICAgICAgIHRhcmdldD0iX2JsYW5rIgogICAgICAgICAgICByZWw9Im5vcmVmZXJyZXIgbm9vcGVuZXIiCiAgICAgICAgICAgIGNsYXNzTmFtZT0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LW5hdnktNzAwIHVuZGVybGluZSIKICAgICAgICAgID4KICAgICAgICAgICAge3QoJ21hcmtldGluZy5jb21wYW55Lm1hcE9wZW5FeHRlcm5hbCcpfQogICAgICAgICAgPC9hPgogICAgICAgICkgOiBudWxsfQogICAgICA8L2Rpdj4KICAgICkKICB9CgogIHJldHVybiAoCiAgICA8aWZyYW1lCg==')],
]);

editar("lang/en/marketing.json", [
    [base64_decode('ICAgICAgIlVTIjogIlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIKICAgIH0sCiAgICAiaG91cnMyNDciOiAiT3BlbiAyNCBob3VycyBhIGRheSwgZXZlcnkgZGF5LiIsCiAgICAiZGlyZWN0aW9ucyI6ICJHZXQgZGlyZWN0aW9ucyDihpIiLAogICAgIm1hcFRpdGxlIjogIk1hcCBvZiBvdXIgb2ZmaWNlIGxvY2F0aW9uIgogIH0KfQo='), base64_decode('ICAgICAgIlVTIjogIlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIKICAgIH0sCiAgICAiaG91cnMyNDciOiAiT3BlbiAyNCBob3VycyBhIGRheSwgZXZlcnkgZGF5LiIsCiAgICAiZGlyZWN0aW9ucyI6ICJHZXQgZGlyZWN0aW9ucyDihpIiLAogICAgIm1hcFRpdGxlIjogIk1hcCBvZiBvdXIgb2ZmaWNlIGxvY2F0aW9uIiwKICAgICJtYXBDb25zZW50IjogIlRoZSBtYXAgaXMgc2VydmVkIGJ5IEdvb2dsZS4gTG9hZGluZyBpdCBzZW5kcyB0aGVtIHlvdXIgSVAgYWRkcmVzcy4gTm90aGluZyBpcyByZXF1ZXN0ZWQgdW50aWwgeW91IGFzayBmb3IgaXQuIiwKICAgICJtYXBMb2FkIjogIlNob3cgdGhlIG1hcCIsCiAgICAibWFwT3BlbkV4dGVybmFsIjogIk9yIG9wZW4gaXQgaW4gR29vZ2xlIE1hcHMiCiAgfQp9Cg==')],
]);

editar("lang/es/marketing.json", [
    [base64_decode('ICAgICAgIlVTIjogIkVzdGFkb3MgVW5pZG9zIGRlIEFtw6lyaWNhIgogICAgfSwKICAgICJob3VyczI0NyI6ICJBYmllcnRvIDI0IGhvcmFzIGFsIGTDrWEsIHRvZG9zIGxvcyBkw61hcy4iLAogICAgImRpcmVjdGlvbnMiOiAiQ8OzbW8gbGxlZ2FyIOKGkiIsCiAgICAibWFwVGl0bGUiOiAiTWFwYSBkZSBsYSB1YmljYWNpw7NuIGRlIG51ZXN0cmEgb2ZpY2luYSIKICB9Cn0K'), base64_decode('ICAgICAgIlVTIjogIkVzdGFkb3MgVW5pZG9zIGRlIEFtw6lyaWNhIgogICAgfSwKICAgICJob3VyczI0NyI6ICJBYmllcnRvIDI0IGhvcmFzIGFsIGTDrWEsIHRvZG9zIGxvcyBkw61hcy4iLAogICAgImRpcmVjdGlvbnMiOiAiQ8OzbW8gbGxlZ2FyIOKGkiIsCiAgICAibWFwVGl0bGUiOiAiTWFwYSBkZSBsYSB1YmljYWNpw7NuIGRlIG51ZXN0cmEgb2ZpY2luYSIsCiAgICAibWFwQ29uc2VudCI6ICJFbCBtYXBhIGxvIHNpcnZlIEdvb2dsZS4gQ2FyZ2FybG8gbGVzIGVudsOtYSBzdSBkaXJlY2Npw7NuIElQLiBObyBzZSBwaWRlIG5hZGEgaGFzdGEgcXVlIHVzdGVkIGxvIHBpZGEuIiwKICAgICJtYXBMb2FkIjogIlZlciBlbCBtYXBhIiwKICAgICJtYXBPcGVuRXh0ZXJuYWwiOiAiTyBhYnJpcmxvIGVuIEdvb2dsZSBNYXBzIgogIH0KfQo=')],
]);

/* ── Parte ───────────────────────────────────────────────────────────────── */

echo $dry ? "SIMULACIÓN (no se escribió nada)\n\n" : "lote25 — documentación y mapa\n\n";
foreach ($hechos as $l) { echo "  {$l}\n"; }
if ($saltados !== []) { echo "\n  ya estaba:\n"; foreach ($saltados as $l) { echo "    {$l}\n"; } }
if ($errores !== []) {
    echo "\nERRORES:\n";
    foreach ($errores as $l) { echo "  ! {$l}\n"; }
    echo "\nNada de lo que falló se escribió a medias.\n";
    exit(1);
}
if (! $dry) { echo <<<'TXT'

Siguiente paso:

  npm run build

No hay migración ni cambios de servidor. La suite no cambia.

TXT; }
exit(0);
