import { describe, expect, it } from 'vitest'
import { tenantDb } from '@/db/tenant-db'
import type { Actor } from '@/lib/permissions'
import { getStorage, __resetStorageForTests } from '@/lib/storage'
import { requestExport, generateExport } from '@/server/exports/service'
import {
  createTestCarrier,
  createTestCustomer,
  createTestLoadWithSnapshot,
  createTestTenant,
  createTestUser,
} from './fixtures'

function dispatcherActor(tenantId: string, userId: string, assignedCarrierIds: string[]): Actor & { tenantId: string } {
  return {
    userId,
    email: 'dispatcher@example.test',
    firstName: 'Dee',
    lastName: 'Dispatcher',
    locale: 'en',
    timezone: 'America/Chicago',
    isPlatformSuperAdmin: false,
    tenantId,
    role: 'dispatcher',
    carrierId: null,
    driverId: null,
    assignments: { carrierIds: assignedCarrierIds, truckIds: [], trailerIds: [], driverIds: [], groupIds: [] },
    overrides: [],
    mfaRequired: false,
    mfaSatisfied: true,
    impersonation: null,
    sessionId: null,
  }
}

const request = { ipAddress: null, userAgent: null, requestId: 'test-request' }

describe('export generation replays the requester\'s snapshotted scope', () => {
  it('never widens access even when generated by a worker with no live actor', async () => {
    __resetStorageForTests()

    const tenant = await createTestTenant()
    const admin = await createTestUser({ firstName: 'Ada', lastName: 'Admin' })
    const dispatcherUser = await createTestUser({ firstName: 'Dee', lastName: 'Dispatcher' })
    const db = tenantDb(tenant.id)

    const assignedCarrier = await createTestCarrier(db, admin.id, { legalName: 'Assigned Carrier LLC' })
    const otherCarrier = await createTestCarrier(db, admin.id, { legalName: 'Other Carrier LLC' })
    const customer = await createTestCustomer(db)

    await createTestLoadWithSnapshot(db, {
      carrierId: assignedCarrier.id,
      customerId: customer.id,
      customerChargeCents: 500_000,
      carrierGrossRateCents: 400_000,
    })
    await createTestLoadWithSnapshot(db, {
      carrierId: otherCarrier.id,
      customerId: customer.id,
      customerChargeCents: 600_000,
      carrierGrossRateCents: 480_000,
    })

    const dispatcher = dispatcherActor(tenant.id, dispatcherUser.id, [assignedCarrier.id])

    const job = await requestExport(db, dispatcher, null, request, {
      reportKey: 'revenue_margin',
      format: 'csv',
      filters: { range: { preset: 'monthly' }, groupBy: 'carrier' },
    })

    // The snapshot records the already-narrowed scope, not the actor's role.
    const snapshot = job.scopeSnapshot as { scope: { kind: string; carrierIds: string[] } }
    expect(snapshot.scope.kind).toBe('assigned')
    expect(snapshot.scope.carrierIds).toEqual([assignedCarrier.id])

    // Generation happens with only (db, jobId) — no Actor at all, simulating
    // a background worker with no logged-in user.
    const completed = await generateExport(db, job.id)
    expect(completed.status).toBe('succeeded')
    expect(completed.storageKey).toBeTruthy()

    const object = await getStorage().get(completed.storageKey!)
    const csv = object.body.toString('utf8')
    expect(csv).toContain('Assigned Carrier LLC')
    expect(csv).not.toContain('Other Carrier LLC')
  })

  it('records export.created and export.downloaded audit events', async () => {
    __resetStorageForTests()

    const tenant = await createTestTenant()
    const admin = await createTestUser({ firstName: 'Ada', lastName: 'Admin' })
    const db = tenantDb(tenant.id)
    const carrier = await createTestCarrier(db, admin.id)
    const customer = await createTestCustomer(db)
    await createTestLoadWithSnapshot(db, { carrierId: carrier.id, customerId: customer.id, carrierGrossRateCents: 100_000 })

    const adminActor: Actor & { tenantId: string } = {
      userId: admin.id,
      email: admin.email,
      firstName: admin.firstName,
      lastName: admin.lastName,
      locale: 'en',
      timezone: 'America/New_York',
      isPlatformSuperAdmin: false,
      tenantId: tenant.id,
      role: 'admin',
      carrierId: null,
      driverId: null,
      assignments: { carrierIds: [], truckIds: [], trailerIds: [], driverIds: [], groupIds: [] },
      overrides: [],
      mfaRequired: false,
      mfaSatisfied: true,
      impersonation: null,
      sessionId: null,
    }

    const job = await requestExport(db, adminActor, null, request, {
      reportKey: 'revenue_margin',
      format: 'csv',
      filters: { range: { preset: 'monthly' }, groupBy: 'carrier' },
    })
    await generateExport(db, job.id)

    const { downloadExport } = await import('@/server/exports/service')
    const download = await downloadExport(db, adminActor, request, job.id)
    expect(download.url).toBeTruthy()

    const { auditEvents } = await import('@/db/schema')
    const { eq, and } = await import('drizzle-orm')
    const events = await db.findMany(auditEvents, {
      where: and(eq(auditEvents.entityType, 'export_job'), eq(auditEvents.entityId, job.id)),
    })
    const actions = events.map((e) => e.action)
    expect(actions).toContain('export.created')
    expect(actions).toContain('export.downloaded')
  })
})
