import ExcelJS from 'exceljs'
import type { Locale } from '@/i18n/config'
import type { TranslateFn } from '@/i18n/translate'
import type { ReportColumn } from '@/server/reports/types'
import { formatCellValue } from './format'

export interface XlsxMetadata {
  generatedByEmail: string
  generatedAt: Date
  reportTitle: string
  filters: Record<string, unknown>
}

const NUMBER_FORMATS: Partial<Record<ReportColumn['type'], string>> = {
  currency: '"$"#,##0.00',
  integer: '#,##0',
  percent: '0.00%',
  bps: '0.00%',
  date: 'm/d/yyyy',
}

/** Cell value for numeric formats: currency and integer stay in their native unit; percent/bps become Excel fractions. */
function numericCellValue(value: unknown, type: ReportColumn['type']): number | Date | string {
  if (value === null || value === undefined) return ''
  if (type === 'date') return value instanceof Date ? value : new Date(String(value))
  if (typeof value === 'string' && value.startsWith('report.')) return value // resolved to text below by caller
  const numeric = Number(value)
  if (Number.isNaN(numeric)) return String(value)
  switch (type) {
    case 'currency':
      return numeric / 100
    case 'percent':
      return numeric / 100
    case 'bps':
      return numeric / 10_000
    case 'integer':
      return numeric
    default:
      return numeric
  }
}

export async function buildXlsx(
  columns: ReportColumn[],
  rows: Array<Record<string, unknown>>,
  locale: Locale,
  t: TranslateFn,
  timeZone: string,
  metadata: XlsxMetadata,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = metadata.generatedByEmail
  workbook.created = metadata.generatedAt

  const sheet = workbook.addWorksheet(metadata.reportTitle.slice(0, 31) || 'Report', {
    views: [{ state: 'frozen', ySplit: 1 }],
  })

  sheet.columns = columns.map((column) => ({
    header: t(column.labelKey),
    key: column.key,
    width: Math.max(14, t(column.labelKey).length + 4),
  }))
  sheet.getRow(1).font = { bold: true }
  sheet.getRow(1).alignment = { vertical: 'middle' }

  for (const row of rows) {
    const record: Record<string, unknown> = {}
    for (const column of columns) {
      const raw = row[column.key]
      if (typeof raw === 'string' && raw.startsWith('report.')) {
        record[column.key] = formatCellValue(raw, column, locale, t, timeZone)
      } else {
        record[column.key] = numericCellValue(raw, column.type)
      }
    }
    sheet.addRow(record)
  }

  for (const column of columns) {
    const format = NUMBER_FORMATS[column.type]
    if (!format) continue
    const col = sheet.getColumn(column.key)
    col.numFmt = format
    col.alignment = { horizontal: column.numeric ? 'right' : 'left' }
  }

  const metaSheet = workbook.addWorksheet('Metadata')
  metaSheet.columns = [
    { header: 'Field', key: 'field', width: 24 },
    { header: 'Value', key: 'value', width: 60 },
  ]
  metaSheet.getRow(1).font = { bold: true }
  metaSheet.addRows([
    { field: 'Report', value: metadata.reportTitle },
    { field: 'Generated by', value: metadata.generatedByEmail },
    { field: 'Generated at', value: metadata.generatedAt.toISOString() },
    { field: 'Filters', value: JSON.stringify(metadata.filters) },
    { field: 'Row count', value: String(rows.length) },
  ])

  const arrayBuffer = await workbook.xlsx.writeBuffer()
  return Buffer.from(arrayBuffer)
}
